### ISSUE TITLE
jsonをレスポンスするリクエストの仕様

### ISSUE THREAD

**Issue by yujiroarai** [hws-wao/core#13]
@kimuramanabu 
ファイルアップロードのところが、jsonレスポンスしてますが、暫定的な仕様だと思います。
jsonをレスポンスさせたい場合の仕様としてこんなのどうでしょう？
### まずwaoアプリにjsonファイルを置く

```
# cat waoapp_8972/api/wao_app_file.json
{ code: <%= @code %> }
```
### jsonファイルのパスにリクエストする

```
Request URL: /api/wao_app_file.json
Request Method: POST
body:
    name=/path/file.html
```
### @のとこに値がbindされて、レスポンスされる

```
{ code: 0 }
```

**Comment by kimuramanabu** [comment]
提案の回答にはなりませんが、GETの場合はクエリストリング
（当然jsonが返るわけではないので、data-wao-bindして使う）
RESTの場合はGET /_FILE/path/to/file.json
みたいな感じで考えていました。

### bindして使う場合

```
http://FQDN:port/hogehoge.html?_FILE=path/to/file.txt
```

``` html
<textarea data-wao-bind="_FILE.path/to/file.txt"></textarea>
```

### jsonを取得する場合

```
http://FQDN:port/_FILE/path/to/file.txt.json
```

**Comment by yujiroarai** [comment]
@kimuramanabu  jsonでレスポンスしてほしいタイミングはAPIとしてWAOを使う場合だと思うので、RESTの場合の話をすると、
1. URLに_FILEが入っていて、WAOアプリだとバレる（WAOで作ってることをセキュリティ的にバレたくない人もいそう）
2. _FILEをURLに入れないといけないことを覚えないといけない（htmlはパスを指定すれば良いだけ）
3. jsonを返すためにtxtを書かないといけない理由がわからない

ので、あんまり良くないと思います。

**Comment by kimuramanabu** [comment]
@yujiroarai 
すみません、いろいろ前提が合っていないですね。。。
file.txt.jsonのパターンはファイル情報を取得するケースで

``` javascript
var _FILE = { "path/to/file.txt": { filename: "file.txt", data: "this is file data." } };
```

みたいなものを想定して書きました。jsonを返却するのにtxtファイルが必要って意味じゃないです。

あと話が少しそれますがAPIのセキュリティはOAuth 2.0とかで
アプリケーション認証をしようかと思ってます。

で、これらの話の前提にあるのはAQUA的な機能で
デバッグするにあたってはDBを参照したいとかファイルがアップロードできたか確認したいとか
そういうのを想定したI/Fについて話してます。
（なので、質問に対する回答になってませんね、ごめんなさい）

json返却するのに荒井さんが言ってる方式は必要だと思います。
加工して出したいパターン。
それとは別にアプリの資産をそのまま返却するI/Fも用意します。
後者の方が先だと思って、その話をしちゃいました。

ちなみにDBにアクセスする場合

```
http://FQDN:port/_DB/collection.json?collection.id=123
```

**Comment by yujiroarai** [comment]
@kimuramanabu 了解です！！ありがとうございます！そのまま返す為のIFの話っていうことを理解して読み返したら、理解出来ました！！

とりあえず、そっちを先に進めて、必要なときにこの話ができればと思います！！

**Comment by hws-aoyagi** [comment]
#44に統合するので、クローズ
