### ISSUE TITLE
AQUAと調整さんの動作確認

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#16]
青柳さんに頼むと品質が良くなるから。

**Comment by yujiroarai** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by hws-aoyagi** [comment]
AQUAで動かせるところは、全て動かし、issueりました。
それらのバグを潰せば、機能面はOKだと思います。
パフォーマンスも気になりますが、それは今後ということで。。
- SHA
  87a67ded557a303a615bb899b6663a4a0cdc330e
