### ISSUE TITLE
バージョンきるのはどーすんの？

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#17]
gitは荒井ちゃんに聞こう！
AQUA v0.2対応はWAO v2.1にします。

**Comment by yujiroarai** [comment]
@kimuramanabu  
あまり良く知らないので、Gitlabのプロジェクトを参考にすると、
1. タグを使って、細かい 1.1.1, 1.2.0, 1.2.1 みたいなバージョンを残す  
   http://www.backlog.jp/git-guide/stepup/stepup5_3.html
2. 1-1-stable, 1-2-stableみたいなバージョン名のブランチを作ってそこで開発を進めるという方法があります。

ブランチ戦略はこの記事がわかりやすいです。
http://postd.cc/gitlab-flow/#gfm-37

**Comment by kimuramanabu** [comment]
他んとこ見てきました。
タグ切ってますね。
タグv2.1.0をどこかのタイミングで作りましょう。
リリースノートも作らなきゃ。readmeに入れる？

**Comment by yujiroarai** [comment]
Changelog.md みたいなとこに書いた方が良いと思います！
Readmeは一発でワオの凄さがわかる資料にしたいです！

**Comment by kimuramanabu** [comment]
@yujiroarai 

> タグv2.1.0をどこかのタイミングで作りましょう。

本日19時時点で作成をお願いします。
Changelog.mdはこちらで作成します。

**Comment by yujiroarai** [comment]
了解です！Changelog.mdありがとうございます！
