### ISSUE TITLE
file.jsをdefferrdで書きなおす

### ISSUE THREAD

**Issue by yujiroarai** [hws-wao/core#2]

**Comment by kimuramanabu** [comment]
エラー処理をfail()で拾うという統一のため。

**Comment by yujiroarai** [comment]
すみません。これは18時に間に合わなそうです。

**Comment by kimuramanabu** [comment]
これはまだオープンのままですか？
残作業があれば報告をお願いします。

**Comment by yujiroarai** [comment]
@kimuramanabu  オープンのままです！これを修正すると、いろんなとこに影響して身動き取れなくなりました！！
遅くなってすみません！昨日からまたコツコツ書きなおしています。

**Comment by kimuramanabu** [comment]
対応しない。
