### ISSUE TITLE
【AQUAバグ】アプリ詳細の情報がbindされない

### ISSUE THREAD

**Issue by hws-aoyagi** [hws-wao/core#27]
### 事象

アプリ一覧から「開く」リンクをクリックし、アプリ詳細を表示した際
詳細画面に選択したアプリの情報が表示されるはずが
データがバインドされておらず、すべて空白となっている
### 再現手順

1.「アプリの管理」画面にてWebアプリを新規作成する
2.作成後、Webアプリ一覧に表示されたアプリの「開く」をクリックする
- SHA
  3d8d49271cb5cd7f2b2edeb425bb53a083dcb4cd

**Comment by yujiroarai** [comment]
:+1: さすが。あおやぎさんからは逃げられない。

**Comment by hws-aoyagi** [comment]
逃がさんぜよ:rage:
とか言って、自分のバグだったりして、、
木村さんが適材適所に修正依頼をするはず！

**Comment by kimuramanabu** [comment]
@yujiroarai 
バグ修正はしたけど、
_FILE.pathのバインドが残ってます。
以前のapp.jsでいう133行目あたり

``` javascript
      if (url_parts.query.hasOwnProperty('_FILE.path')) {
        // ディレクトリの情報を取得
        WaoPageFactory().readDirRecursive('./templates/' + url_parts.query['_FILE.path'], function(fileList) {
          that.findData._FILE = fileList;
          dbconnect();
        });
      }
```

このあたりの処理をbind前に実行して_FILE.pathに入れておいてください。

**Comment by yujiroarai** [comment]
了解です！あさってくらいまでにやります！！

**Comment by yujiroarai** [comment]
@kimuramanabu これって、ディレクトリ構造を_FILE.path に入れるっていう話ですよね？？

**Comment by yujiroarai** [comment]
> ディレクトリ構造を_FILE.path に入れる

という修正は終わりました！

**Comment by hws-aoyagi** [comment]
SHA-1: 0aaf9f46f0170f10db8f781a2cfc0f7c1db5a4be
で再確認しました。
当初の「アプリ詳細の情報がbindされない問題」は解消していて
選択したアプリの情報がアプリ詳細に表示されることは確認しました。
ですが、_FILE.pathが、どのアプリでも「/chousei_8888/」のままです。
※別で起票すべきかもしれませんが、このラインで話が出てたので記票しません。

```
<a href="directory.html?webapp.id=14243611211097642&amp;_FILE.path=/chousei_8888/" class="btn btn-app">
  <i class="fa fa-code"></i> HTML
</a>
```

**Comment by yujiroarai** [comment]
@hws-aoyagi  AQUA更新しました！？

**Comment by hws-aoyagi** [comment]
@yujiroarai 
AQUA更新してませんでした。。#28 に書いてありましたね。
更新してやってみます！ありがとうございます。

**Comment by hws-aoyagi** [comment]
_FILE.path直ってました！
当初のバグと_FILE.pathがOKなので、他の問題は残っていますが
このissueはクローズします！
