### ISSUE TITLE
【AQUAバグ】HTMLアップロード画面が表示できない

### ISSUE THREAD

**Issue by hws-aoyagi** [hws-wao/core#28]
### 事象

アプリ詳細画面から「HTML」をクリックすると画面遷移せず、タイムアウトする
### 再現手順

1.任意のアプリのアプリの詳細画面を開く
2.画面上部の「HTML」リンクをクリックする
### 備考

「HTML」のリンクが下記URLとなっており、webapp.idがバインドされていなかった
また、アプリの名前は、myapp_8001で作成したにも関わらず、「chousei_8888」となっている
http://localhost:8686/webapp/directory.html?webapp.id=&_FILE.path=/chousei_8888/
- SHA
  3d8d49271cb5cd7f2b2edeb425bb53a083dcb4cd

**Comment by kimuramanabu** [comment]
@hws-aoyagi 
対象データのダンプください。
`db.webapp.find({port:8888});`
の結果みたいな感じ。

**Comment by kimuramanabu** [comment]
ダンプの件、取り消し。
#29 と同じだと思う。

**Comment by kimuramanabu** [comment]
そもそもアクセス先を制限したから値を変えないと。
&_FILE.path=/chousei_8888/

**Comment by yujiroarai** [comment]
> また、アプリの名前は、myapp_8001で作成したにも関わらず、「chousei_8888」となっている

これは、AQUA側を修正しました。 3e626af80e4d08adcbb2d30c98517b82c2a74b8c

bind前のHTMLで、HTML内のjavascriptが実行されて、_FILE.path=にchousei_8888が設定されていたんだと思われます。jsを外部ファイルにして、一旦この問題は起こらなくしました。

**Comment by hws-aoyagi** [comment]
@yujiroarai 
あれ！？すいません。。
masterじゃなくて、houndciで確認するんでしたっけ？

**Comment by yujiroarai** [comment]
masterでOKです！

**Comment by hws-aoyagi** [comment]
アプリ詳細画面から「HTML」をクリックした際、HTMLアップロード画面に遷移するようになったことを確認したので、クローズします。
