### ISSUE TITLE
【AQUAバグ】アプリ詳細画面の「起動する」で画面がリロードされる

### ISSUE THREAD

**Issue by hws-aoyagi** [hws-wao/core#29]
### 事象

アプリ詳細画面から「起動する」をクリックURLが書き換わる
http://localhost:8686/webapp/detail.html?webapp.id=14237834919002263
↓
http://localhost:8686/webapp/detail.html?webapp.id=
### 再現手順

1.任意のアプリのアプリの詳細画面を開く
2.画面上部の「起動する」リンクをクリックする
### 備考

ファイルアップロードが行えていない為、実際の起動確認は行えていないが
ソースを確認したところ、アプリ起動を行うformのパラメータが正しくない。
data-wao-bind-data-port="webapp.portが残ったままで
name="_APP.undefined:undefined"となっている。（アプリ名:ポート、となるはず）
data-appid=""→アプリIDが入るはず。

``` formタグ抜粋
<form action="detail.html?webapp.id=" method="post" style="display:inline">
  <button class="btn btn-app btn-success">
    <i class="fa fa-play-circle"></i> 起動する
  </button>
  <input class="webapp-start" type="hidden" data-wao-bind-data-port="webapp.port" value="start()" name="_APP.undefined:undefined" data-appid="">
</form>
```
- SHA
  3d8d49271cb5cd7f2b2edeb425bb53a083dcb4cd

**Comment by kimuramanabu** [comment]
@hws-aoyagi 
あ！
そーゆーことか。
response_builder.jsの59行目以降、

``` javascript
          var $ = result._FILE.template;
          $('html').wao_bind({
            'bindData' : {
              '_DB'   : result._DB,
              '_FILE' : result._FILE
            }
          });
```

バインド用の資産をDBとFILEしか渡してないからだ。
APPもバインドできる形で渡してあげないと。

あおやぎさん、対応可能？

**Comment by kimuramanabu** [comment]
あれ。。。違ったorz
bindしたはずのデータが取得でけてない。。。とか。そんな感じだな。
webappの格納先は_DBか。資産の指定はこれで十分っぽい。
あとはwebappがちゃんと_DBに入っているかを確認。

**Comment by hws-aoyagi** [comment]
@kimuramanabu 
すいません。2/19(木)までは手が付けられそうにありません。。
取り急ぎ、下記アドレスにアクセスした際のresultのdumpを張ります。
_DBには、webappの情報は入っていそうです。配列なのが、問題ですか？！
（response_builder#buildでブレイク）
http://localhost:8686/webapp/detail.html?webapp.id=14237834919002263

```
{"_FILE":{"ext":".html"},"_DB":{"webapp":[{"_id":"54dd3643b5c061a01ea0a912","name":"調整さん","app_id":"myapp","port":"8001","note":"WAO V2最初に登録するアプリです\r\nどうでしょ？","id":"1423783491900
2263","_createdDate":1423783491900}]}}
```

**Comment by kimuramanabu** [comment]
@hws-aoyagi 
修正したから試してみて！

**Comment by hws-aoyagi** [comment]
- SHA
  b703a83ebb6b8dcd3199dc9681ec3d2198e079dc
  アプリ名は入るようになりましたが、ポートがまだダメです。。

```
<form action="detail.html?webapp.id=" method="post" style="display:inline">
  <button class="btn btn-app btn-success">
    <i class="fa fa-play-circle"></i> 起動する
  </button>
  <input class="webapp-start" type="hidden" data-wao-bind-data-port="webapp.port" value="start()" name="_APP.chosuke:undefined" data-appid="chosuke">
</form>
```

**Comment by kimuramanabu** [comment]
ぬぬ？！
同じタグに複数bind-attrがあると
２個目以降が無視されるとか？
ってたぶんそうだと思う。。。。。。
対応します！

**Comment by kimuramanabu** [comment]
@hws-aoyagi 
87a67ded557a303a615bb899b6663a4a0cdc330e
ご確認をば、やらしくお願いします。

**Comment by hws-aoyagi** [comment]
アプリ一覧からの遷移直後のbindはOKとなりました！

```
  <input class="webapp-start" type="hidden" value="start()" data-appid="chosuke" data-port="8765" name="_APP.chosuke:8765">
```

ただし、「起動する」をクリックすると画面がリロードされ、リロードされた後はbindされなくなります。
画面にアプリの情報は表示されています。
また、アプリの起動も出来ていません。

```
  <input class="webapp-start" type="hidden" data-wao-bind-data-appid="webapp.app_id" data-wao-bind-data-port="webapp.port" value="start()" name="_APP.undefined:undefined">
```

**Comment by hws-aoyagi** [comment]
ちょーすけさん起動出来ました！！
起動した後のアプリ詳細画面の表示もOKです。
クローズします。
