### ISSUE TITLE
[DB]クエリストリング＞mongoのオペランドに対応

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#3]
?col.prop=key&col.prop$gt=123

?$or=(&col.prop=key&col.prop$gt=123&$or=)

?col.find={$or:{col.prop:"key",col.prop:{$gt:123}}

こんな感じ？
今後も要検討。

**Comment by hws-aoyagi** [comment]
http://docs.mongodb.org/manual/reference/operator/query/
Logicalまでやる

**Comment by hws-aoyagi** [comment]
I/Fは下記にしようと思います。
[or[__ {group_name} ]**] {collection.field_name} [** {operand} ]

$eq：field_name__eq ⇒ operand省略時と等価
$gt：field_name__gt
$gte：field_name__gte
$lt：field_name__lt
$lte：field_name__lte
$ne：field_name__ne
$in：field_name__in ⇒ field_nameが同じものが複数あったら、inにしてもよい
$nin：field_name__nin

$or：group_nameによって、orで接続する条件を判断する。group_nameは省略も可。
$and：name属性にorが含まれていない場合は、and

例）
col1.price=1000
SQL:price = 1000

col1.price__ge=1000&col1.price__le=5000
SQL:price >= 1000 and price <= 5000

or__col1.color=black&or__col1.color=white
SQL:color = 'black' or color = 'white'

or__g1__col1.color=black&or__g1__col1.color=white&or__g2__col1.blood_type=A&or__g2__col1.blood_type=B
SQL:(color = 'black' or color = 'white') and (blood_type = 'A' or blood_type = 'B')

**Comment by kimuramanabu** [comment]
'__'（アンダースコア２文字）は禁則文字列。
これをドキュメント名やフィールド名に指定してはいけない。
（指定されている場合はエラーにする）
→ INSERTとUPDATEでチェック処理を行う。

<input type="hidden" name="user.id=_SES.user.id" data-wao="inner" />

get_handler.jsを基本的には修正していく。（モジュール構成は要見直し）
refereみて、送信元テンプレートからinnerフォームを取得（例：user.id=_SES.user.id）して
getパラメタ（POSTデータ含む）の条件として追加する。

**Comment by hws-aoyagi** [comment]
Logicalの$not、$norを除くオペランドまで対応しました。
残タスクは、禁則文字列と内部条件への対応です。
