### ISSUE TITLE
【AQUAバグ】HTMLアップロード画面にファイル一覧が表示されない

### ISSUE THREAD

**Issue by hws-aoyagi** [hws-wao/core#31]
### 事象

アプリ詳細画面から「HTML」をクリックし、HTMLアップロード画面に遷移した際
ファイル一覧が表示されるはずが、表示されない。
### 再現手順

1.wao-coreをpullし、apps配下にchosuke_8765を取得する。
2.アプリの新規作成で「ちょ～すけサン」の情報を登録する。
　WEBアプリケーション名：任意
　WEBアプリケーションID：chosuke
　使用するポート番号：8765
3.アプリ一覧から「ちょ～すけサン」の「開く」リンクをクリックし、アプリ詳細を開く
4.アプリ詳細画面上部の「HTML」リンクをクリックする
### data dump

{ "_id" : ObjectId("54e606fb6cd804b42200f1b9"), "name" : "ちょうすけ", "app_id" : "chosuke", "port" : "8765", "note" : "ちょうすけ\r\nちょうすけ\r\nちょうすけ", "id" : "1424361211168701", "_createdDate" : 1424361211168 }
- SHA
  87a67ded557a303a615bb899b6663a4a0cdc330e

**Comment by yujiroarai** [comment]
@kimuramanabu @hws-aoyagi 
wao_bindプラグインをどうやって修正すれば治るのかは、もうちょっとソースを読まないとわからなかったので、とりあえずいまのwao_bindプラグインで動くように修正しました！

1d0dd94

**Comment by kimuramanabu** [comment]
昨日の夜、なおったと思ったんですが
いまはファイルの一覧が表示できていません。

**Comment by yujiroarai** [comment]
えー！！！すみません！！！
