### ISSUE TITLE
【ちょ〜すけサン】イベントと回答が登録できない

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#33]
親と子が登録できない。
親はinsert。
子はupdate。

**Comment by hws-aoyagi** [comment]
暫定的な処理ですが、回答を登録（update）できるようになりました！
9d5df1bb44fe488fdcae45f8dc1a75925b389497

ですが、以下の３つの問題が残っています。
1) ○×△のどれを選択しても、全て○で登録されてしまう
    schedule\list.htmlのjavascriptの問題！？

2) イベント登録後のrefresh時にidが付与されない
    イベント登録後にPOSTしたデータを返却するようにしましたが
    create.htmlのevent.idがbindされません。。
    試しにcreate.htmlでrefreshさせないでsapnタグを追加してdata-wao-bindしたら、idが表示されました。
   metaタグへのbindが上手くいってない模様です。

3) inputタグへbind出来ない
    updateの為にidをhiddenタグに出力しようとしましたが
    inputタグにはbind出来ないようです。idをspanタグにしたら、出力されました。

**Comment by hws-aoyagi** [comment]
@kimuramanabu 
上記の問題について、明日引き続き調査しますが
木村さんの方で何か気づいたことがあれば教えてください。
特に2)と3)のbind系。

**Comment by hws-aoyagi** [comment]
@kimuramanabu 
3) の対応完了しました。今度こそ回答が登録できます。
2730e7e63e56b32a1e373711365558537b318ecc

1)　は、bind-data.jsに宣言されている_USRなるものがない事が問題のようです。
仕様を把握しきれていないので、1)の対応も木村さんにお願いしたいです。
