### ISSUE TITLE
サンプルアプリのwao-bind.jsはsubmoduleにする

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#34]
lib/client/wao-bind.jsとapps/chosuke_8765/_LOCAL/wao-bind.jsは同じもの。
前者をコミットしたら後者が更新されるようにしたい。

**Comment by hws-aoyagi** [comment]
出来たらやる

**Comment by kimuramanabu** [comment]
いったんやらない方向でクローズ。
