### ISSUE TITLE
jQueryを初期化するUtility関数を作成する

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#4]
``` javascript
var Jquery = require('wao-jquery');
var $ = new Jquery('<html></html>');
```

こんな感じのやつ。

**Comment by kimuramanabu** [comment]
Node.jsで動かすjQueryは2.x系が良いみたい。
URLはconfigに持っていこう。

**Comment by kimuramanabu** [comment]
URLをconfigに移してないけどクローズしちゃうw
この関数の中でjQueryプラグインをくっつけちゃえばいいかな。
scriptタグを生成するだけでいいみたい。
srcはどのパスから始まるのかは謎。

**Comment by yujiroarai** [comment]
:+1:

**Comment by kimuramanabu** [comment]
80adba2208346f8246cc84ac1f1258280dee7598
