### ISSUE TITLE
JSONをレスポンスする

### ISSUE THREAD

**Issue by hws-aoyagi** [hws-wao/core#44]
まずはDBから取得したものを返却する

**Comment by hws-aoyagi** [comment]
data-wao-bind="_DB.{コレクション名}"

**Comment by kimuramanabu** [comment]
`http://FQDN/_DB/collection.json?collection.id=123`

OAuth 2.0 に対応。

**Comment by hws-aoyagi** [comment]
JSONレスポンスの仕様決めました。
方針として、htmlにbindする際の仕様に合わせようと思います。

## DB

#### 特定コレクション全件取得

http://FQDN:port/_DB.{collection}.json

#### 条件指定

http://FQDN:port/_DB.json?{collection}.{field}=123（複数コレクションの同時取得可）

#### コレクション一覧

http://FQDN:port/_DB._collections.json

## FILE

#### ファイルパス、内容取得

http://FQDN:port/_FILE.{file_path}.json

#### ディレクトリの内容を取得

http://FQDN:port/_FILE.{dir_path}.json

**Comment by kimuramanabu** [comment]
@aoyagi:
@hws-aoyagi 

> #### ファイルパス取得
> 
> http://FQDN:port/_FILE.{file_path}._path.json
> 
> #### ファイル内容取得
> 
> http://FQDN:port/_FILE.{file_path}._body.json

これって以下の意味じゃないですか？

#### ファイル情報取得

http://FQDN:port/_FILE.{file_path}.json

```
{
  _path: '/res/2qw3e4r5t6y7u8i9o0.txt',
  _body: 'contents...'
}
```

ちなみに対象ファイルがjsonだと `hoge.json.json` ですね。なんかびみょーw

**Comment by hws-aoyagi** [comment]
ファイルパス指定で、非公開ディレクトリのパスと内容を返却するようにしました。
http://FQDN:port/_FILE.{file_path}.json

```
{
  _path: '/res/2qw3e4r5t6y7u8i9o0.txt',
  _body: 'contents...'
}
```

**Comment by hws-aoyagi** [comment]
残タスク
ファイルのパスと内容が取れない時がある。要調査。

**Comment by hws-aoyagi** [comment]
DB、FILE情報ともjson返却できるようになったのでクローズします。
