### ISSUE TITLE
暗号化機能

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#51]
パスワードを保存するには暗号化しないと。。。
追加タスクで申し訳ありませんが、合宿中の期限とします。
よろしくです！！

**Comment by hws-aoyagi** [comment]
単一フィールドに対して登録、更新、検索時に暗号化する処理を追加しました。

パスワードの暗号化には対応可能ですが
$in、$ninとドキュメント内配列の登録、更新に対応できていませんので
まだ完璧ではありません。。
