### ISSUE TITLE
開発のときはファイルをキャッシュしないようにしたい

### ISSUE THREAD

**Issue by yujiroarai** [hws-wao/core#52]
node-dev で起動しても、毎回サーバー停止→起動しないと反映されない。

**Comment by kimuramanabu** [comment]
これは更新を監視するようにしたいです。

**Comment by yujiroarai** [comment]
:+1:

**Comment by kimuramanabu** [comment]
https://github.com/hws-wao/core/blob/master/lib/response/builder.js#L80
すでにこの辺りで実装済みだったりする。
