### ISSUE TITLE
メール送信機能

### ISSUE THREAD

**Issue by kimuramanabu** [hws-wao/core#7]
まずはアーキテクトの大枠を決めないと。。。

**Comment by kimuramanabu** [comment]
アーキテクトは以下でいいかな。
http://qiita.com/yoh-nak/items/1e433b0075e3ebdef9e3

## WAOの仕様まとめ

### HTML

```
<input name="_MAIL.to" value="hoge@hoge.hoge" />
<input name="_MAIL.to" value="hoge@hoge.hoge" data-wao="inner" />
```

### 指定可能なフォーム

_MAIL.to
_MAIL.cc
_MAIL.bcc
_MAIL.from
_MAIL.subject
_MAIL.body

### フォーム値の仕様

文字コードはutf8
メールアドレスはカンマ区切りで複数指定可能
メールアドレス記述形式：`hoge@hoge.hoge`　または　`ほげ<hoge@hoge.hoge>`

### アプリ初期化時に指定するパラメタ

MTAのホスト名（またはIPアドレス）
ポート番号
SMTP認証情報（メアド、パス）　→これは送信ごとかな？fromに依存

### サーバー商品として

AQUAが稼働しているサーバーにMTAを立てておく
→ 適正な転送設定も行う

### デバッグ機能

メールを出したフリしてログファイルに出力とか

**Comment by hws-aoyagi** [comment]
SMTP認証に対応できてません。
